[email]
sender_email = "your-email@gmail.com"
sender_password = "your-16-digit-app-password"

[drive_apps_script]
web_app_url = "https://script.google.com/macros/s/AKfycbzYtmoGiVklvVQaOc1womEiYI7E-Yt6_gi6Q8HgaYR_Bnqv1Hya2AceWk3k8-_uv73ZwQ/exec"
folder_id = ""  # اختياري - سيحفظ في root